# Generated by Django 3.2.7 on 2021-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocerries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grocerries_Image', models.ImageField(upload_to='')),
                ('Grocerries_Name', models.CharField(max_length=50)),
                ('Grocerries_Weight', models.FloatField()),
                ('Grocerries_Price', models.FloatField()),
            ],
        ),
    ]
