# Generated by Django 3.2.7 on 2021-09-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_meals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerries',
            name='Grocerries_Weight',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meals',
            name='Meals_quantity',
            field=models.CharField(max_length=50),
        ),
    ]
